### PR TITLE
Use replacable values when possible

### PR DESCRIPTION
**Pull request by swadeley**
Hi @JunqiZhang0 

Its not good to expose internal URLs, it makes people nervous at least. Also, when using values you want the user to replace (replacables), use <replace_me> in text files, and _replace_me_ where better markup is available.

Thank you

### CODE REVIEW

**Review by rplevka — APPROVED** [review]

**Comment by JunqiZhang0** [comment]
Hey @swadeley , thank you for submitting PR! tfacon has been moved to https://github.com/RedHatQE/tfacon, you can submit PR there.

**Comment by swadeley** [comment]
> Hey @swadeley , thank you for submitting PR! tfacon has been moved to https://github.com/RedHatQE/tfacon, you can submit PR there.

I can do that, but you still need to accept this PR or remove this repo from public view.

**Comment by swadeley** [comment]
Sorry, did not mean to close, let me know if you want it reopened.

**Comment by swadeley** [comment]
https://github.com/RedHatQE/tfacon/pull/22

**Pull request closed without merging**
